### ISSUE TITLE
Some issues 

### ISSUE THREAD

**Issue by Shichiha** [WeismannS/Genshin-Achievement-Maker#1]
## your gitignore is in the wrong encoding so you committed `node_modules`
fix by saving in `UTF-8` and deleting `node_modules`

## ~~the assets folder should be stored in root dir~~
~~(actually im not so sure about this 😄)~~
## there are path issues with linux
(did you only test it on windows..?), they can be fixed using the path module, e.g:
```ts
import path from 'path'
...
registerFont(path.join(__dirname, "..", 'assets', 'zh-cn.ttf'), { family: 'genshin' })
...
const myimg = await loadImage(path.join(__dirname, "..", 'assets', 'row-2-column-1.png'))
```
then enabling `esModuleInterop` in tsconfig settings

---
i made a fork to fix all of these so if you want i could PR them

**Comment by WeismannS** [comment]
Thank you for bringing this issue to my attention shichihachi! I have not tested on linux sadly , this will be fixed in a second
